### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by chrisdolan** [jezhumble/javasysmon#18]
The docs say "JavaSysMon uses the NetBSD (2-line) license." but the source code includes a  license file with copyright attributed to Thoughtworks. Could you please clarify? And possibly could you change the build to include a LICENSE and NOTICE file in the jar?

**Comment by jezhumble** [comment]
Both of those statements are true: the copyright is held by ThoughtWorks,
and ThoughtWorks licenses the code under the NetBSD license.

When I get some time I'll update the build. Meanwhile, if it's especially
important to you, I'll happily merge a pull request that includes those
changes.

On 20 August 2012 11:45, Chris Dolan notifications@github.com wrote:

> The docs say "JavaSysMon uses the NetBSD (2-line) license." but the source
> code includes a license file with copyright attributed to Thoughtworks.
> Could you please clarify? And possibly could you change the build to
> include a LICENSE and NOTICE file in the jar?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jezhumble/javasysmon/issues/18.

## 

Jez Humble
Co-author, _Continuous Delivery http://continuousdelivery.com/_
http://continuousdelivery.com/
http://jezhumble.net/

**Comment by chrisdolan** [comment]
Got it. Thanks for the clarification!
