### ISSUE TITLE
build error on String.isEmpty() in NativeLibraryLoad.java

### ISSUE THREAD

**Issue by jafingerhut** [jezhumble/javasysmon#6]
I replaced the call to isEmpty() to checking if the length() is equal to 0, and things compile fine:

diff --git a/src/main/java/com/jezhumble/javasysmon/NativeLibraryLoader.java b/src/main/java/com/jezhumble/javasysmon/NativeLibraryLoader.java
index 6a658cd..602b9a2 100644
--- a/src/main/java/com/jezhumble/javasysmon/NativeLibraryLoader.java
+++ b/src/main/java/com/jezhumble/javasysmon/NativeLibraryLoader.java
@@ -45,7 +45,7 @@ class NativeLibraryLoader {

```
 private File createTempFile(String suffix, String prefix) throws IOException {
     String tempDirProp = System.getProperty(JAVA_SYS_MON_TEMP_DIR);
```
-        if (tempDirProp == null || tempDirProp.isEmpty()) {
-        if (tempDirProp == null || tempDirProp.length() == 0) {
           return File.createTempFile(prefix, suffix);
       }
       return File.createTempFile(prefix, suffix, new File(tempDirProp));

**Comment by itspanzi** [comment]
Hey,

isEmpty is a Java 1.6 feature and does not work on 1.5. But I guess just to do an isEmpty, we should not enforce 1.6! :)

**Comment by jezhumble** [comment]
Fixed. Thanks for the bug report.
